Update GitHub workflows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,51 +3,177 @@
 #   Will skip without error if not present.
 # CurseForge publishing requires a CurseForge API token `CURSEFORGE_TOKEN`
 #   Will skip without error if not present.
-# Preference using the root gradle.properties file to configure releases.
+# Release version and other properties are set via the root `gradle.properties` file.
 name: Release
-
-on:
-  workflow_dispatch:
-
 permissions:
   contents: write
 
+on:
+  workflow_dispatch:
+    inputs:
+      fabric:
+        type: boolean
+        description: Publish Fabric Version
+        required: true
+        default: true
+      neoforge:
+        type: boolean
+        description: Publish NeoForge Version
+        required: true
+        default: true
+      github:
+        type: boolean
+        description: Publish to GitHub
+        required: true
+        default: true
+      modrinth:
+        type: boolean
+        description: Publish to Modrinth
+        required: true
+        default: true
+      curseforge:
+        type: boolean
+        description: Publish to CurseForge
+        required: true
+        default: true
+      java:
+        type: choice
+        description: Java Version
+        required: true
+        options:
+          - '25'
+          - '21'
+          - '17'
+        default: '25'
+      os:
+        type: choice
+        description: Operating System
+        required: true
+        options:
+          - 'ubuntu-latest'
+          - 'windows-latest'
+        default: 'ubuntu-latest'
+
 jobs:
   release:
-    strategy:
-      matrix:
-        java: [
-          25
-        ]
-        os: [
-          ubuntu-latest
-        ]
-    runs-on: ${{ matrix.os }}
+    runs-on: ${{ inputs.os }}
+
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v5
+      # Log the workflow input values for future reference.
+      - name: Log workflow inputs
+        run: |
+          echo '${{ toJson(inputs) }}' | jq .
+
+      # Retrieve and store the current Git branch name for future use.
+      - name: Extract branch name
+        id: ref
+        shell: bash
+        # bash pattern expansion to grab branch name without slashes
+        run: ref="${GITHUB_REF#refs/heads/}" && echo "branch=${ref////-}" >> $GITHUB_OUTPUT
+
+      # Checkout the repository under $GITHUB_WORKSPACE, so the workflow can access it.
+      # https://github.com/actions/checkout
+      - name: Checkout sources
+        uses: actions/checkout@v6
         with:
+          # Number of commits to fetch. 0 indicates all history for all branches and tags.
+          # Default: 1
           fetch-depth: 0
-      - name: Validate Gradle wrapper
-        uses: gradle/actions/wrapper-validation@v5
-      - name: Setup JDK ${{ matrix.java }}
+
+      # Setup Java for the build.
+      # https://github.com/actions/setup-java
+      - name: Setup JDK ${{ inputs.java }}
         uses: actions/setup-java@v5
         with:
-          distribution: zulu
-          java-version: ${{ matrix.java }}
+          distribution: temurin
+          java-version: ${{ inputs.java }}
+
+      # Setup Gradle for the build.
+      # https://github.com/gradle/actions/blob/main/setup-gradle
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v6
+
       - name: Make Gradle wrapper executable
-        if: ${{ runner.os != 'Windows' }}
+        if: runner.os != 'Windows'
         run: chmod +x ./gradlew
-      - name: Build
-        run: ./gradlew build neoforge:publishGithub neoforge:publishCurseforge neoforge:publishModrinth fabric:publishGithub fabric:publishCurseforge fabric:publishModrinth --stacktrace
+
+      # Build the project; subsequent publish tasks will reuse this compilation.
+      - name: Build project
+        shell: bash
+        run: ./gradlew build --stacktrace
+
+      # Upload build artifacts to the workflow report.
+      # https://github.com/actions/upload-artifact
+      - name: Capture build artifacts
+        uses: actions/upload-artifact@v7
+        with:
+          name: ${{ github.event.repository.name }}-artifacts-${{ steps.ref.outputs.branch }}
+          path: |
+            **/build/libs/*.jar
+            !buildSrc/**
+            !common/**
+
+      # Publish artifacts, continuing on error. Incurs reconfiguration overhead.
+      - name: NeoForge GitHub
+        id: neoforge_github
+        shell: bash
+        if: inputs.neoforge && inputs.github
+        continue-on-error: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: ./gradlew neoforge:publishGithub --stacktrace
+      - name: NeoForge Modrinth
+        id: neoforge_modrinth
+        shell: bash
+        if: inputs.neoforge && inputs.modrinth
+        continue-on-error: true
+        env:
           MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
+        run: ./gradlew neoforge:publishModrinth --stacktrace
+      - name: NeoForge CurseForge
+        id: neoforge_curseforge
+        shell: bash
+        if: inputs.neoforge && inputs.curseforge
+        continue-on-error: true
+        env:
           CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
-      - name: Capture build artifacts
-        if: ${{ runner.os == 'Linux' && matrix.java == '25' }}
-        uses: actions/upload-artifact@v5
-        with:
-          name: artifacts
-          path: |
-            **/build/libs/
+        run: ./gradlew neoforge:publishCurseforge --stacktrace
+      - name: Fabric GitHub
+        id: fabric_github
+        shell: bash
+        if: inputs.fabric && inputs.github
+        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: ./gradlew fabric:publishGithub --stacktrace
+      - name: Fabric Modrinth
+        id: fabric_modrinth
+        shell: bash
+        if: inputs.fabric && inputs.modrinth
+        continue-on-error: true
+        env:
+          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
+        run: ./gradlew fabric:publishModrinth --stacktrace
+      - name: Fabric CurseForge
+        id: fabric_curseforge
+        shell: bash
+        if: inputs.fabric && inputs.curseforge
+        continue-on-error: true
+        env:
+          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
+        run: ./gradlew fabric:publishCurseforge --stacktrace
+
+      # Finally, check for publishing errors and fail the task if one was found.
+      - name: Check publishing errors
+        shell: bash
+        if: |
+          steps.neoforge_github.outcome == 'failure' ||
+          steps.neoforge_modrinth.outcome == 'failure' ||
+          steps.neoforge_curseforge.outcome == 'failure' ||
+          steps.fabric_github.outcome == 'failure' ||
+          steps.fabric_modrinth.outcome == 'failure' ||
+          steps.fabric_curseforge.outcome == 'failure'
+        run: |
+          echo "Detected an error in a publish task: check the Summary for details"
+          exit 1
+
